USE QLNhaHang
GO

-- RESET AUTO_INCREAMENT
IF exists (SELECT * FROM AREA)				DBCC CHECKIDENT (AREA,				RESEED, 0)
IF exists (SELECT * FROM CART)				DBCC CHECKIDENT (CART,				RESEED, 0)
IF exists (SELECT * FROM CUSTOMER)			DBCC CHECKIDENT (CUSTOMER,			RESEED, 0)
IF exists (SELECT * FROM DISH)				DBCC CHECKIDENT (DISH,				RESEED, 0)
IF exists (SELECT * FROM INVENTORYITEM)		DBCC CHECKIDENT (INVENTORYITEM,		RESEED, 0)
IF exists (SELECT * FROM [ORDER])			DBCC CHECKIDENT ([ORDER],			RESEED, 0)
IF exists (SELECT * FROM ORDERSTATUS)		DBCC CHECKIDENT (ORDERSTATUS,		RESEED, 0)
IF exists (SELECT * FROM PAYMENT)			DBCC CHECKIDENT (PAYMENT,			RESEED, 0)
IF exists (SELECT * FROM RESERVATION)		DBCC CHECKIDENT (RESERVATION,		RESEED, 0)
IF exists (SELECT * FROM RESERVATIONLIST)	DBCC CHECKIDENT (RESERVATIONLIST,	RESEED, 0)
IF exists (SELECT * FROM RESERVATIONSTATUS) DBCC CHECKIDENT (RESERVATIONSTATUS, RESEED, 0)
IF exists (SELECT * FROM STAFF)				DBCC CHECKIDENT (STAFF,				RESEED, 0)
IF exists (SELECT * FROM STAFFTYPE)			DBCC CHECKIDENT (STAFFTYPE,			RESEED, 0) 
IF exists (SELECT * FROM [TABLE])			DBCC CHECKIDENT ([TABLE],			RESEED, 0) 
IF exists (SELECT * FROM TABLETYPE)			DBCC CHECKIDENT (TABLETYPE,			RESEED, 0) 
IF exists (SELECT * FROM WORKDAY)			DBCC CHECKIDENT (WORKDAY,			RESEED, 0) 
IF exists (SELECT * FROM WORKSHIFT)			DBCC CHECKIDENT (WORKSHIFT,			RESEED, 0) 

-- DELETE DATA FROM TABLES
--DELETE FROM CHITIETPHIEUTRA
DELETE FROM AREA				
DELETE FROM RESERVATIONORDER				
DELETE FROM CARTDETAIL				
DELETE FROM WEEKLYSHIFT				
DELETE FROM CART			
DELETE FROM CUSTOMER		
DELETE FROM DISH		
DELETE FROM INVENTORYITEM		
DELETE FROM [ORDER]	
DELETE FROM ORDERSTATUS		
DELETE FROM PAYMENT		
DELETE FROM RESERVATION		
DELETE FROM RESERVATIONLIST	
DELETE FROM RESERVATIONSTATUS 
DELETE FROM STAFF			
DELETE FROM STAFFTYPE			
DELETE FROM [TABLE]		
DELETE FROM TABLETYPE	
DELETE FROM WORKDAY		
DELETE FROM WORKSHIFT		

INSERT INTO CUSTOMER VALUES 
('DUC','1','098009',NULL,'10/10/2003',NULL,'NHT-Q7-TPHCM'),
('YEN','1','098809',NULL,'10/30/2003',NULL,'DONGHOI-QB')