USE QLNhaHang
GO
CREATE TRIGGER trg_newCart_OnCustomerInsert
ON CUSTOMER
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO CART (ID_CUSTOMER)
    SELECT ID_CUSTOMER
    FROM INSERTED;
END

GO 

CREATE TRIGGER TRG_CREATEPAYROLLDETAIL_ONSTAFFINSERT
ON STAFF
AFTER INSERT
AS
BEGIN
    SET NOCOUNT ON;

    DECLARE @MONTH SMALLINT = MONTH(GETDATE());
    DECLARE @YEAR SMALLINT = YEAR(GETDATE());

    DECLARE @IDPAYROLL INT;

    -- 1. Kiểm tra PAYROLL tháng hiện tại đã tồn tại chưa
    SELECT @IDPAYROLL = ID_PAYROLL
    FROM PAYROLL
    WHERE [MONTH] = @MONTH AND [YEAR] = @YEAR;

    -- 2. Nếu chưa có, tạo mới
    IF @IDPAYROLL IS NULL
    BEGIN
        INSERT INTO PAYROLL ([MONTH], [YEAR])
        VALUES (@MONTH, @YEAR);

        SET @IDPAYROLL = SCOPE_IDENTITY();
    END

    -- 3. Thêm PAYROLLDETAIL cho mỗi nhân viên vừa thêm
    INSERT INTO PAYROLLDETAIL (
        ID_STAFF,
        ID_PAYROLL
    )
    SELECT 
        I.ID_STAFF,
        @IDPAYROLL
    FROM INSERTED I;
END;
